# Generated by Django 5.2.3 on 2025-07-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_productflag_product_productphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productflag',
            options={'verbose_name': 'Флаг продукта', 'verbose_name_plural': 'Флаги продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='default', max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
