# Generated by Django 5.2.3 on 2025-07-04 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, help_text='Телефон для связи с продавцом или службой поддержки', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?[\\d\\s\\-\\(\\)]{9,20}$')], verbose_name='Телефон'),
        ),
    ]
