# Generated by Django 5.2.3 on 2025-07-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_product_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flags',
        ),
        migrations.AddField(
            model_name='product',
            name='is_children',
            field=models.BooleanField(blank=True, default=False, verbose_name='Детское'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_electronics',
            field=models.BooleanField(blank=True, default=False, verbose_name='Электроника'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_home_appliances',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бытовая техника'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_laptops',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ноутбуки'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='На главную'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_other',
            field=models.BooleanField(blank=True, default=False, verbose_name='Другое'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_precious_metals',
            field=models.BooleanField(blank=True, default=False, verbose_name='Драгоценные металлы'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sport_tourism',
            field=models.BooleanField(blank=True, default=False, verbose_name='Спорт/Туризм'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tools',
            field=models.BooleanField(blank=True, default=False, verbose_name='Инструменты'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tv',
            field=models.BooleanField(blank=True, default=False, verbose_name='Телевизоры'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_watches',
            field=models.BooleanField(blank=True, default=False, verbose_name='Часы'),
        ),
        migrations.DeleteModel(
            name='ProductFlag',
        ),
    ]
