# Generated by Django 5.2.3 on 2025-07-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_financialstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='year',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='name',
            field=models.CharField(default='Имя и Год', max_length=255, verbose_name='Название'),
        ),
    ]
