# Generated by Django 5.2.3 on 2025-07-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_financialstatement_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='year',
            field=models.PositiveIntegerField(default='2000', verbose_name='Год'),
        ),
    ]
