# Generated by Django 5.2.3 on 2025-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_financialstatement_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='name',
            field=models.CharField(default='Имя', max_length=255, verbose_name='Название'),
        ),
    ]
