# Generated by Django 5.2.3 on 2025-07-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_financialstatement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('working_hours', models.CharField(help_text='Например: Пн-Пт 9:00-18:00', max_length=100, verbose_name='Время работы')),
                ('lunch_break', models.CharField(blank=True, help_text='Например: 13:00-13:45', max_length=100, verbose_name='Обед')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='locations/photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
