# Generated by Django 5.2.3 on 2025-07-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Время работы')),
                ('lunch_break', models.CharField(blank=True, max_length=100, verbose_name='Обед')),
                ('phones', models.JSONField(verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='addresses/photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='webapp.city', verbose_name='Город'),
        ),
    ]
