# Generated by Django 5.2.3 on 2025-07-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_city_options_city_slug_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название соцсети')),
                ('icon', models.CharField(help_text='CSS класс для иконки, например vk, instagram, telegram', max_length=50, verbose_name='Иконка (CSS класс)')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
                'ordering': ['name'],
            },
        ),
    ]
