# Generated by Django 5.2.3 on 2025-09-25 15:37

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_socialnetwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='documents/registration_certificate/', verbose_name='Свидетельство о регистрации')),
                ('registry_inclusion_certificate', models.FileField(blank=True, null=True, upload_to='documents/registry_inclusion_certificate/', verbose_name='Свидетельство о включении в реестр')),
                ('charter', models.FileField(blank=True, null=True, upload_to='documents/charter/', verbose_name='Устав')),
                ('microloan_agreement', models.FileField(blank=True, null=True, upload_to='documents/microloan_agreement/', verbose_name='Договор микрозайма')),
                ('pledge_ticket', models.FileField(blank=True, null=True, upload_to='documents/pledge_ticket/', verbose_name='Залоговый билет')),
                ('microloan_rules', models.FileField(blank=True, null=True, upload_to='documents/microloan_rules/', verbose_name='Правила предоставления микрозаймов')),
                ('loyalty_program_regulation', models.FileField(blank=True, null=True, upload_to='documents/loyalty_program_regulation/', verbose_name='Положение о программе лояльности')),
                ('microloan_types', models.FileField(blank=True, null=True, upload_to='documents/microloan_types/', verbose_name='Виды предоставления микрозаймов')),
                ('ministry_of_finance_license', models.FileField(blank=True, null=True, upload_to='documents/ministry_of_finance_license/', verbose_name='Лицензия министерства финансов')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='icon',
            field=models.FileField(help_text='Загрузите SVG или изображение (PNG, JPG)', upload_to=webapp.models.icon_upload_path, verbose_name='Иконка (SVG или изображение)'),
        ),
    ]
